server:
  port: 8080
spring:
  application:
    name: single
  #  cloud:
  #    nacos:
  #      server-addr: 10.200.114.5:8848
  datasource:
    url: jdbc:mysql://10.10.20.242:3306/code-generator?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
    username: root
    password: aaaaaa
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      filters: stat,wall
      initial-size: 10
      max-active: 500
      max-pool-prepared-statement-per-connection-size: 20
      max-wait: 60000
      min-evictable-idle-time-millis: 300000
      min-idle: 10
      pool-prepared-statements: true
      stat-view-servlet:
        enabled: true
        login-password: admin
        login-username: admin
        reset-enable: true
        url-pattern: /druid/*
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      validation-query: SELECT 'x'
      web-stat-filter:
        enabled: true
        exclusions: '"*.js , *.gif ,*.jpg ,*.png ,*.css ,*.ico , /druid/*"'
        profile-enable: true
        session-stat-enable: false
        session-stat-max-count: 1000
        url-pattern: /*
  main:
    allow-bean-definition-overriding: true
#  redis:
#    host: 127.0.0.1
#    lettuce:
#      pool:
#        max-active: 8
#        max-idle: 8
#        max-wait: -1
#        min-idle: 0
#    port: 6379
#    timeout: 5000

feign:
  client:
    config:
      feignName:
        connectTimeout: 30000
        readTimeout: 30000
  compression:
    request:
      enabled: true
      mime-types: text/xml,application/xml,application/json
      min-request-size: 2048
    response:
      enabled: true
  httpclient:
    enabled: false
    max-connections: 1000
    max-connections-per-route: 100
  hystrix:
    enabled: false
  okhttp:
    enabled: true
  sentinel:
    enabled: true
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
mybatis-plus:
  configuration:
    cache-enabled: false
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      field-strategy: NOT_NULL
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto
  mapper-locations: classpath:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.central.common.model

ribbon:
  ConnectTimeout: 30000
  MaxAutoRetriesNextServer: 0
  ReadTimeout: 30000
  ServerListRefreshInterval: 15000


logging:
  level:
    com.sdnydb.creditReporting:
      debug
